# Generated by Django 4.2.7 on 2025-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250731_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='region',
            name='type',
            field=models.CharField(choices=[('region', 'Область'), ('city', 'Город республиканского подчинения'), ('republic', 'Республика')], default='region', max_length=20),
        ),
    ]
