# Generated by Django 4.2.23 on 2026-03-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_videocall_videocallsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdi_number', models.IntegerField(choices=[(11, 'Upper Right 11'), (12, 'Upper Right 12'), (13, 'Upper Right 13'), (14, 'Upper Right 14'), (15, 'Upper Right 15'), (16, 'Upper Right 16'), (17, 'Upper Right 17'), (18, 'Upper Right 18'), (21, 'Upper Left 21'), (22, 'Upper Left 22'), (23, 'Upper Left 23'), (24, 'Upper Left 24'), (25, 'Upper Left 25'), (26, 'Upper Left 26'), (27, 'Upper Left 27'), (28, 'Upper Left 28'), (31, 'Lower Left 31'), (32, 'Lower Left 32'), (33, 'Lower Left 33'), (34, 'Lower Left 34'), (35, 'Lower Left 35'), (36, 'Lower Left 36'), (37, 'Lower Left 37'), (38, 'Lower Left 38'), (41, 'Lower Right 41'), (42, 'Lower Right 42'), (43, 'Lower Right 43'), (44, 'Lower Right 44'), (45, 'Lower Right 45'), (46, 'Lower Right 46'), (47, 'Lower Right 47'), (48, 'Lower Right 48')])),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('filled', 'Filled'), ('crowned', 'Crowned'), ('missing', 'Missing'), ('implant', 'Implant'), ('damaged', 'Damaged'), ('decayed', 'Decayed'), ('root_canal', 'Root Canal Treated'), ('bridge', 'Bridge'), ('veneer', 'Veneer'), ('extracted', 'Extracted'), ('impacted', 'Impacted'), ('under_treatment', 'Under Treatment')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='authentication.dentalchart')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teeth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fdi_number'],
                'unique_together': {('chart', 'fdi_number')},
            },
        ),
        migrations.CreateModel(
            name='ToothTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('examination', 'Examination'), ('filling', 'Filling'), ('composite_filling', 'Composite Filling'), ('amalgam_filling', 'Amalgam Filling'), ('crown', 'Crown'), ('root_canal', 'Root Canal Treatment'), ('extraction', 'Extraction'), ('implant', 'Implant'), ('implant_crown', 'Implant Crown'), ('bridge', 'Bridge'), ('veneer', 'Veneer'), ('whitening', 'Whitening'), ('scaling', 'Scaling & Cleaning'), ('xray', 'X-Ray'), ('orthodontic', 'Orthodontic Treatment'), ('sealant', 'Sealant'), ('bonding', 'Bonding'), ('other', 'Other')], max_length=30)),
                ('treatment_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('materials_used', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_visit_recommended', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_treatments', to=settings.AUTH_USER_MODEL)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='authentication.tooth')),
            ],
            options={
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.CreateModel(
            name='ToothXray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dental_xrays/')),
                ('file_type', models.CharField(choices=[('xray', 'X-Ray'), ('photo', 'Photo'), ('scan', '3D Scan')], default='xray', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='authentication.tooth')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrays', to='authentication.toothtreatment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_xrays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
