# Generated by Django 4.2.23 on 2026-03-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_dentalchart_tooth_toothtreatment_toothxray'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeizureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seizure_type', models.CharField(choices=[('tonic_clonic', 'Tonic-Clonic (Grand Mal)'), ('absence', 'Absence (Petit Mal)'), ('focal', 'Focal Seizure'), ('myoclonic', 'Myoclonic'), ('atonic', 'Atonic (Drop Attack)'), ('tonic', 'Tonic'), ('clonic', 'Clonic'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('consciousness', models.CharField(choices=[('full', 'Fully Conscious'), ('partial', 'Partially Conscious'), ('lost', 'Lost Consciousness')], default='lost', max_length=10)),
                ('warning_signs', models.TextField(blank=True)),
                ('potential_trigger', models.CharField(blank=True, max_length=200)),
                ('body_parts_affected', models.JSONField(blank=True, default=list)),
                ('fell_down', models.BooleanField(default=False)),
                ('injury_occurred', models.BooleanField(default=False)),
                ('injury_description', models.TextField(blank=True)),
                ('recovery_time_minutes', models.IntegerField(blank=True, null=True)),
                ('post_seizure_symptoms', models.TextField(blank=True)),
                ('emergency_services_called', models.BooleanField(default=False)),
                ('witnessed_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seizure_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_seizures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='NeurologyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('symptoms_reported', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('medications_prescribed', models.JSONField(blank=True, default=list)),
                ('tests_ordered', models.JSONField(blank=True, default=list)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurology_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='HeadacheDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headache_type', models.CharField(choices=[('tension', 'Tension Headache'), ('migraine', 'Migraine'), ('cluster', 'Cluster Headache'), ('sinus', 'Sinus Headache'), ('rebound', 'Rebound Headache'), ('thunderclap', 'Thunderclap Headache'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('location', models.CharField(choices=[('front', 'Front of head'), ('back', 'Back of head'), ('left', 'Left side'), ('right', 'Right side'), ('both_sides', 'Both sides'), ('top', 'Top of head'), ('around_eye', 'Around eye'), ('whole_head', 'Whole head')], default='whole_head', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('light_sensitivity', models.BooleanField(default=False)),
                ('sound_sensitivity', models.BooleanField(default=False)),
                ('aura', models.BooleanField(default=False)),
                ('aura_description', models.TextField(blank=True)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('medication_taken', models.CharField(blank=True, max_length=200)),
                ('medication_helped', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headache_diary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
