# Generated by Django 4.2.23 on 2026-03-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_medication_patientmedication_medicationintakelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('routine', 'Routine Eye Exam'), ('emergency', 'Emergency Visit'), ('follow_up', 'Follow-up'), ('pre_surgery', 'Pre-Surgery Assessment'), ('post_surgery', 'Post-Surgery Check'), ('contact_lens', 'Contact Lens Fitting'), ('pediatric', 'Pediatric Eye Exam')], default='routine', max_length=20)),
                ('va_right_eye', models.CharField(blank=True, max_length=20)),
                ('va_left_eye', models.CharField(blank=True, max_length=20)),
                ('va_right_corrected', models.CharField(blank=True, max_length=20)),
                ('va_left_corrected', models.CharField(blank=True, max_length=20)),
                ('iop_right', models.FloatField(blank=True, null=True)),
                ('iop_left', models.FloatField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('next_exam_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_eye_exams', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='VisionPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_type', models.CharField(choices=[('glasses', 'Glasses'), ('contact_lens', 'Contact Lens'), ('both', 'Both')], default='glasses', max_length=15)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('right_sphere', models.FloatField(blank=True, null=True)),
                ('right_cylinder', models.FloatField(blank=True, null=True)),
                ('right_axis', models.IntegerField(blank=True, null=True)),
                ('right_add', models.FloatField(blank=True, null=True)),
                ('right_pd', models.FloatField(blank=True, null=True)),
                ('left_sphere', models.FloatField(blank=True, null=True)),
                ('left_cylinder', models.FloatField(blank=True, null=True)),
                ('left_axis', models.IntegerField(blank=True, null=True)),
                ('left_add', models.FloatField(blank=True, null=True)),
                ('left_pd', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_vision_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='authentication.eyeexam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='EyeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('myopia', 'Myopia (Nearsightedness)'), ('hyperopia', 'Hyperopia (Farsightedness)'), ('astigmatism', 'Astigmatism'), ('presbyopia', 'Presbyopia'), ('glaucoma', 'Glaucoma'), ('cataract', 'Cataract'), ('macular_degeneration', 'Macular Degeneration'), ('diabetic_retinopathy', 'Diabetic Retinopathy'), ('dry_eye', 'Dry Eye Syndrome'), ('conjunctivitis', 'Conjunctivitis'), ('strabismus', 'Strabismus'), ('amblyopia', 'Amblyopia (Lazy Eye)'), ('retinal_detachment', 'Retinal Detachment'), ('keratoconus', 'Keratoconus'), ('other', 'Other')], max_length=30)),
                ('affected_eye', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], default='both', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('managed', 'Managed'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=15)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_eye_conditions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
