# Generated by Django 4.2.23 on 2026-03-08 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_eyeexam_visionprescription_eyecondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('hypertension', 'Hypertension'), ('coronary_artery_disease', 'Coronary Artery Disease'), ('heart_failure', 'Heart Failure'), ('atrial_fibrillation', 'Atrial Fibrillation'), ('arrhythmia', 'Arrhythmia'), ('valve_disease', 'Heart Valve Disease'), ('cardiomyopathy', 'Cardiomyopathy'), ('pericarditis', 'Pericarditis'), ('myocarditis', 'Myocarditis'), ('congenital', 'Congenital Heart Defect'), ('angina', 'Angina'), ('heart_attack', 'Heart Attack (MI)'), ('stroke', 'Stroke'), ('dvt', 'Deep Vein Thrombosis'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('managed', 'Managed'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=15)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_heart_conditions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('rhythm', models.CharField(choices=[('normal_sinus', 'Normal Sinus Rhythm'), ('sinus_tachycardia', 'Sinus Tachycardia'), ('sinus_bradycardia', 'Sinus Bradycardia'), ('atrial_fibrillation', 'Atrial Fibrillation'), ('atrial_flutter', 'Atrial Flutter'), ('svt', 'Supraventricular Tachycardia'), ('ventricular_tachycardia', 'Ventricular Tachycardia'), ('heart_block', 'Heart Block'), ('paced', 'Paced Rhythm'), ('other', 'Other')], default='normal_sinus', max_length=30)),
                ('pr_interval', models.FloatField(blank=True, null=True)),
                ('qrs_duration', models.FloatField(blank=True, null=True)),
                ('qt_interval', models.FloatField(blank=True, null=True)),
                ('qtc_interval', models.FloatField(blank=True, null=True)),
                ('axis', models.CharField(blank=True, max_length=50)),
                ('interpretation', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('ecg_file', models.FileField(blank=True, null=True, upload_to='ecg_files/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpreted_ecgs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardiologyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('examination_findings', models.TextField(blank=True)),
                ('medications_prescribed', models.JSONField(blank=True, default=list)),
                ('tests_ordered', models.JSONField(blank=True, default=list)),
                ('lifestyle_recommendations', models.TextField(blank=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiology_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodPressureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('sitting', 'Sitting'), ('standing', 'Standing'), ('lying', 'Lying Down')], default='sitting', max_length=10)),
                ('arm', models.CharField(choices=[('left', 'Left Arm'), ('right', 'Right Arm'), ('both', 'Both Arms')], default='left', max_length=10)),
                ('measured_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_logs', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_bp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
