# Generated by Django 4.2.23 on 2026-03-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_heartcondition_ecgrecord_cardiologyvisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthoCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('fracture', 'Fracture'), ('dislocation', 'Dislocation'), ('sprain', 'Sprain'), ('strain', 'Strain/Muscle Tear'), ('tendinitis', 'Tendinitis'), ('bursitis', 'Bursitis'), ('arthritis', 'Arthritis'), ('osteoporosis', 'Osteoporosis'), ('herniated_disc', 'Herniated Disc'), ('scoliosis', 'Scoliosis'), ('carpal_tunnel', 'Carpal Tunnel Syndrome'), ('rotator_cuff', 'Rotator Cuff Injury'), ('acl_injury', 'ACL Injury'), ('meniscus_tear', 'Meniscus Tear'), ('plantar_fasciitis', 'Plantar Fasciitis'), ('osteoarthritis', 'Osteoarthritis'), ('rheumatoid_arthritis', 'Rheumatoid Arthritis'), ('back_pain', 'Back Pain'), ('neck_pain', 'Neck Pain'), ('other', 'Other')], max_length=30)),
                ('body_part', models.CharField(choices=[('spine', 'Spine'), ('neck', 'Neck'), ('shoulder_left', 'Left Shoulder'), ('shoulder_right', 'Right Shoulder'), ('elbow_left', 'Left Elbow'), ('elbow_right', 'Right Elbow'), ('wrist_left', 'Left Wrist'), ('wrist_right', 'Right Wrist'), ('hand_left', 'Left Hand'), ('hand_right', 'Right Hand'), ('hip_left', 'Left Hip'), ('hip_right', 'Right Hip'), ('knee_left', 'Left Knee'), ('knee_right', 'Right Knee'), ('ankle_left', 'Left Ankle'), ('ankle_right', 'Right Ankle'), ('foot_left', 'Left Foot'), ('foot_right', 'Right Foot'), ('pelvis', 'Pelvis'), ('ribs', 'Ribs'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('healing', 'Healing'), ('chronic', 'Chronic'), ('resolved', 'Resolved'), ('post_surgery', 'Post Surgery')], default='active', max_length=15)),
                ('severity', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('injury_date', models.DateField(blank=True, null=True)),
                ('injury_cause', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_ortho_conditions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortho_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrthoSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_type', models.CharField(choices=[('arthroplasty', 'Joint Replacement (Arthroplasty)'), ('arthroscopy', 'Arthroscopy'), ('acl_reconstruction', 'ACL Reconstruction'), ('spinal_fusion', 'Spinal Fusion'), ('discectomy', 'Discectomy'), ('fracture_repair', 'Fracture Repair/ORIF'), ('tendon_repair', 'Tendon Repair'), ('rotator_cuff_repair', 'Rotator Cuff Repair'), ('meniscus_repair', 'Meniscus Repair'), ('carpal_tunnel_release', 'Carpal Tunnel Release'), ('amputation', 'Amputation'), ('bone_graft', 'Bone Graft'), ('other', 'Other')], max_length=30)),
                ('body_part', models.CharField(max_length=20)),
                ('surgery_date', models.DateField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('successful', 'Successful'), ('partial', 'Partial Success'), ('complicated', 'Complicated'), ('revision_needed', 'Revision Needed')], default='successful', max_length=20)),
                ('complications', models.TextField(blank=True)),
                ('implants_used', models.CharField(blank=True, max_length=300)),
                ('rehabilitation_required', models.BooleanField(default=True)),
                ('rehabilitation_duration_weeks', models.IntegerField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='authentication.orthocondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortho_surgeries', to=settings.AUTH_USER_MODEL)),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_ortho_surgeries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-surgery_date'],
            },
        ),
        migrations.CreateModel(
            name='RehabilitationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('frequency_per_week', models.IntegerField(default=3)),
                ('exercises', models.JSONField(blank=True, default=list)),
                ('goals', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('pain_level_start', models.IntegerField(blank=True, null=True)),
                ('pain_level_current', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehab_plans', to='authentication.orthocondition')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rehab_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plans', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehab_plans', to='authentication.orthosurgery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrthoImaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('bone_scan', 'Bone Scan'), ('dexa', 'DEXA Scan (Bone Density)')], max_length=15)),
                ('body_part', models.CharField(max_length=20)),
                ('imaging_date', models.DateField()),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ortho_imaging/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging', to='authentication.orthocondition')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_ortho_imaging', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortho_imaging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imaging_date'],
            },
        ),
    ]
