# Generated by Django 4.2.23 on 2026-03-08 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_orthocondition_orthosurgery_rehabilitationplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birth_weight_kg', models.FloatField(blank=True, null=True)),
                ('birth_height_cm', models.FloatField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(choices=[('bcg', 'BCG (Tuberculosis)'), ('hepb', 'Hepatitis B'), ('dtap', 'DTaP (Diphtheria, Tetanus, Pertussis)'), ('ipv', 'IPV (Polio)'), ('hib', 'Hib (Haemophilus influenzae)'), ('pcv', 'PCV (Pneumococcal)'), ('rotavirus', 'Rotavirus'), ('mmr', 'MMR (Measles, Mumps, Rubella)'), ('varicella', 'Varicella (Chickenpox)'), ('hepa', 'Hepatitis A'), ('meningococcal', 'Meningococcal'), ('hpv', 'HPV'), ('flu', 'Influenza (Flu)'), ('covid', 'COVID-19'), ('other', 'Other')], max_length=20)),
                ('dose_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('overdue', 'Overdue'), ('skipped', 'Skipped')], default='completed', max_length=15)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('reactions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='authentication.childprofile')),
            ],
            options={
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='PediatricVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('well_child', 'Well-Child Checkup'), ('sick_visit', 'Sick Visit'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('developmental', 'Developmental Assessment'), ('vaccination', 'Vaccination Visit')], default='well_child', max_length=20)),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('developmental_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications_prescribed', models.JSONField(blank=True, default=list)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pediatric_visits', to='authentication.childprofile')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pediatric_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('age_months', models.IntegerField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('head_circumference_cm', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='authentication.childprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_growth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
    ]
