# Generated by Django 4.2.23 on 2026-03-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_childprofile_vaccinationrecord_pediatricvisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Emergency)')], default='routine', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hematology', 'Hematology (CBC)'), ('biochemistry', 'Biochemistry'), ('urine', 'Urinalysis'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology/Serology'), ('hormones', 'Hormones/Endocrinology'), ('coagulation', 'Coagulation'), ('tumor_markers', 'Tumor Markers'), ('vitamins', 'Vitamins & Minerals'), ('cardiac', 'Cardiac Markers'), ('lipids', 'Lipid Panel'), ('liver', 'Liver Function'), ('kidney', 'Kidney Function'), ('thyroid', 'Thyroid Function'), ('diabetes', 'Diabetes Panel'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('result_unit', models.CharField(blank=True, max_length=50)),
                ('reference_range_min', models.FloatField(blank=True, null=True)),
                ('reference_range_max', models.FloatField(blank=True, null=True)),
                ('reference_range_text', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('abnormal_flag', models.CharField(blank=True, choices=[('H', 'High'), ('L', 'Low'), ('HH', 'Critical High'), ('LL', 'Critical Low'), ('A', 'Abnormal')], max_length=5)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='authentication.laborder')),
            ],
            options={
                'ordering': ['category', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('ai_interpretation', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('is_reviewed_by_doctor', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='authentication.laborder')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
