# Generated by Django 4.2.23 on 2026-03-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_medcity_meddistrict_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
