# Generated by Django 4.2.23 on 2026-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_remove_old_city_district'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='authenticat_doctor__70417b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='authenticat_patient_4d6b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='authenticat_status_c501aa_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'status'], name='authenticat_doctor__825562_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'status'], name='authenticat_patient_cb1656_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['created_at'], name='authenticat_created_9cc6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['consultation', 'created_at'], name='authenticat_consult_bcff65_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='authenticat_recipie_bc768a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='authenticat_created_617f15_idx'),
        ),
    ]
