# Generated by Django 4.2.23 on 2026-03-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
